fix code coverage report (#59)

diff --git a/.github/workflows/unit-tests.yml b/.github/workflows/unit-tests.yml
--- a/.github/workflows/unit-tests.yml
+++ b/.github/workflows/unit-tests.yml
@@ -29,14 +29,26 @@ jobs:
       with:
         dotnet-version: ${{ matrix.dotnet.version }}
 
-    - name: Restore
-      run: dotnet restore $SOLUTION
+    - name: Run tests
+      run: |
+        dotnet tool install --global Microsoft.CodeCoverage.Console
 
-    - name: Build
-      run: dotnet build $SOLUTION --configuration $BUILD_CONFIG --no-restore
+        dotnet test $SOLUTION -s .runsettings --configuration $BUILD_CONFIG --framework ${{ matrix.dotnet.tfm }} --logger trx --results-directory "TestResults" /maxcpucount:1 /p:CollectCoverage=true /p:CoverletOutputFormat="cobertura" /p:CoverletOutput="./TestResults/coverage" --verbosity normal
 
-    - name: Test
-      run: dotnet test $SOLUTION --configuration $BUILD_CONFIG --no-build --verbosity normal --framework ${{ matrix.dotnet.tfm }} --logger trx --results-directory "TestResults" /maxcpucount:1 /p:CollectCoverage=true /p:CoverletOutput="../TestResults/" /p:MergeWith="../TestResults/coverage.json" /p:CoverletOutputFormat="cobertura"
+        MERGED_REPORT_PATH="./FinalCoverageReport/coverage.cobertura.xml"
+
+        echo "Creating directory: $(dirname "$MERGED_REPORT_PATH")"
+        mkdir -p "$(dirname "$MERGED_REPORT_PATH")"
+
+        echo "Searching for coverage files..."
+        find . -path '*/TestResults/coverage.cobertura.xml' -print0 | xargs -0 codecoverage merge -o "$MERGED_REPORT_PATH" -f cobertura
+
+        if [ $? -eq 0 ]; then
+          echo "Coverage files successfully merged into: $MERGED_REPORT_PATH"
+        else
+          echo "Error during coverage file merge."
+          exit 1
+        fi
 
     - name: Create Test Coverage Badge
       uses: gaelgirodon/ci-badges-action@v1
